### ISSUE TITLE
Как развернуть это на openshift?

### ISSUE THREAD

**Issue by Yolkis** [Karasiq/webm-tv#2]
Хочу развернуть на openshift, дабы не ебать твою демку

**Comment by Karasiq** [comment]
Но она и так на опеншифте.

**Comment by Yolkis** [comment]
Вроде там какие-то лимиты есть

**Comment by Karasiq** [comment]
[Как-то так](https://docs.openshift.com/container-platform/3.4/dev_guide/managing_images.html)
```
oc import-image webm-tv --from=docker.io/pistonkarasiq/webm-tv
